### ISSUE TITLE
Plugin Preferences -> Choose spell check language 

### ISSUE THREAD

**Issue by raducoravu** [danielnaber/oxygen-languagetool-plugin#3]
In the plugin's preferences page we should have a combo box in which users would select the language used for spell checking.
We could query the server using:

 https://languagetool.org:8081/Languages

but also have a list of default values if the server cannot be contacted.

**Comment by danielnaber** [comment]
I think we should consider `lang` and `xml:lang`, just as the built-in spell checker does.

**Comment by danielnaber** [comment]
We now use `lang` and `xml:lang` if available, otherwise we fall back to the default language configured for the spell checker.
