### ISSUE TITLE
Possibly better segmenation for checked text

### ISSUE THREAD

**Issue by raducoravu** [danielnaber/oxygen-languagetool-plugin#6]
In an XML document some elements may be considered inline (like bold, italic, underline). Ideally when checking a paragraph's text (paragraph containing inline elements) the server should receive the entire text from the paragraph as if those inline elements would not be present.

We could use this API method:

ro.sync.ecss.extensions.api.AuthorDocumentController.getFilteredContent(int, int, AuthorNodesFilter)

which should do this (it was developed for another external spell checker integration) instead of creating those ranges. But this needs to be tested though.

**Comment by danielnaber** [comment]
This has been implemented now.
